// This file is auto-generated by @hey-api/openapi-ts

export const ActionInfoSchema = {
    required: ['actionAllowAnonymous', 'actionName', 'actionPolicies', 'assemblyFullName', 'assemblyName', 'controllerAllowAnonymous', 'controllerName', 'controllerPolicies', 'template'],
    type: 'object',
    properties: {
        template: {
            type: 'string'
        },
        assemblyName: {
            type: 'string'
        },
        assemblyFullName: {
            type: 'string'
        },
        controllerName: {
            type: 'string'
        },
        actionName: {
            type: 'string'
        },
        controllerPolicies: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        actionPolicies: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        controllerAllowAnonymous: {
            type: 'boolean'
        },
        actionAllowAnonymous: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;