// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetActionsError, GetActionsResponse } from './types.gen';

export const client = createClient(createConfig());

export class UmbracoCommunitySecurityAuthPolicyBrowserService {
    public static getActions<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetActionsResponse, GetActionsError, ThrowOnError>({
            ...options,
            url: '/umbraco/umbracocommunitysecurityauthpolicybrowser/api/v1/actions'
        });
    }
    
}