// This file is auto-generated by @hey-api/openapi-ts

export type ActionInfo = {
    template: string;
    assemblyName: string;
    assemblyFullName: string;
    controllerName: string;
    actionName: string;
    controllerPolicies: Array<(string)>;
    actionPolicies: Array<(string)>;
    controllerAllowAnonymous: boolean;
    actionAllowAnonymous: boolean;
};

export type GetActionsResponse = (Array<(ActionInfo)>);

export type GetActionsError = (unknown);